### ISSUE TITLE
Map function also takes a buffer/string

### ISSUE THREAD

**Issue by njordhov** [clarity-lang/reference#14]
The `map` function is [documented in the reference](https://docs.blockstack.org/core/smart/clarityref#map) to take a `list` as argument, but it can also take a `buffer` as argument. The reference should be updated accordingly. Note that the function correctly returns a list in either case. See also issue #7 on buffers and lists being sequences.

Example:

```clojure
(define-read-only (identity (x (buff 1))) x) 
(map identity "abc")
```
=>
```
(0x61 0x62 0x63)
```

**Comment by friedger** [comment]
Can be closed. Fixed in current documentation
