### ISSUE TITLE
Sequential let binding

### ISSUE THREAD

**Issue by njordhov** [clarity-lang/reference#20]
Sequential  binding in `let` will make Clarity code more readable, avoiding nested `let` forms just to be able to refer to earlier bindings.

Clarity currently fails when using sequential variable binding, such as when a variable is calculated using a previously bound variable in a let form:

```clojure
(let ((foo 42)
      (bar (- foo 5)))
  (+ foo bar))
```

More: https://github.com/blockstack/stacks-blockchain/issues/1269

**Comment by kantai** [comment]
This was implemented in Clarity in Stacks 2.0
