### ISSUE TITLE
Newline escape for string literals

### ISSUE THREAD

**Issue by njordhov** [clarity-lang/reference#23]
String literals should support a `\n` escape character for _newline_.

Currently, line breaks in string literals are typed as actual newline characters, violating the formatting/indent of the code and obfuscating whitespace trailing the line before the newline:

```clojure
(define-constant newline "
")

(define-read-only (hello-world)
  (let ((text "Hello World!              
Another line"))
    text))
```

With newline escapes:

```clojure
(define-constant newline "\n")

(define-read-only (hello-world)
  (let ((text "Hello World!\nAnother line"))
    text))
```

**Comment by psq** [comment]
You should be able to use `\u{0A}` with the new string support.  Not sure the `0` is required, although `\n` is shorter...

**Comment by njordhov** [comment]
> although \n is shorter...

... and likely the escape expected/recognized by many developers for newline.

**Comment by lgalabru** [comment]
Thank you @njordhov! This issue was addressed with https://github.com/blockstack/stacks-blockchain/pull/1779 (https://github.com/blockstack/stacks-blockchain/pull/1779/commits/0e995a99156f85b2b23e918af9af601572b70575).
Will close, feel free to re-open if you had something different in mind.

**Comment by njordhov** [comment]
@lgalabru Thanks for taking care of implementing the newline escape. Are newline characters still allowed in strings or restricted to the escape character? I favor the latter for Clarity.
