### ISSUE TITLE
Native string type

### ISSUE THREAD

**Issue by diwakergupta** [clarity-lang/reference#3]
Implement a string type(s) in Clarity. This type would be used in many areas where the buffer type is currently used.

Context:
- https://github.com/blockstack/stacks-blockchain/issues/1504

**Comment by njordhov** [comment]
The default string type should be UTF-8 and just named `String` rather than have an explicit type suffix.

**Comment by njordhov** [comment]
How can we avoid having a separate `u"Hello World"` syntax for UTF-8 strings?

**Comment by njordhov** [comment]
Why the angel brackets around escaped character codes?

```clojure
u"hello \u{1234}"
```
