### ISSUE TITLE
Native cryptographic primitives

### ISSUE THREAD

**Issue by diwakergupta** [clarity-lang/reference#4]
To support use-cases that tie on-chain and off-chain activity (e.g. decentralized oracles), we need native cryptographic primitives (e.g. secp256k1 signature operations).

Context:
- https://github.com/blockstack/stacks-blockchain/issues/1134

**Comment by friedger** [comment]
What is missing to close this issue @diwakergupta ?

**Comment by hugocaillard** [comment]
Merged in https://github.com/stacks-network/stacks-blockchain/pull/1832
